// Code generated by mockery v2.23.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IArchiveFile is an autogenerated mock type for the IArchiveFile type
type IArchiveFile struct {
	mock.Mock
}

type IArchiveFile_Expecter struct {
	mock *mock.Mock
}

func (_m *IArchiveFile) EXPECT() *IArchiveFile_Expecter {
	return &IArchiveFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *IArchiveFile) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IArchiveFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type IArchiveFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *IArchiveFile_Expecter) Close() *IArchiveFile_Close_Call {
	return &IArchiveFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *IArchiveFile_Close_Call) Run(run func()) *IArchiveFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IArchiveFile_Close_Call) Return(_a0 error) *IArchiveFile_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IArchiveFile_Close_Call) RunAndReturn(run func() error) *IArchiveFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: p
func (_m *IArchiveFile) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IArchiveFile_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type IArchiveFile_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *IArchiveFile_Expecter) Read(p interface{}) *IArchiveFile_Read_Call {
	return &IArchiveFile_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *IArchiveFile_Read_Call) Run(run func(p []byte)) *IArchiveFile_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *IArchiveFile_Read_Call) Return(n int, err error) *IArchiveFile_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *IArchiveFile_Read_Call) RunAndReturn(run func([]byte) (int, error)) *IArchiveFile_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Readdirnames provides a mock function with given fields: n
func (_m *IArchiveFile) Readdirnames(n int) ([]string, error) {
	ret := _m.Called(n)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]string, error)); ok {
		return rf(n)
	}
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IArchiveFile_Readdirnames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readdirnames'
type IArchiveFile_Readdirnames_Call struct {
	*mock.Call
}

// Readdirnames is a helper method to define mock.On call
//   - n int
func (_e *IArchiveFile_Expecter) Readdirnames(n interface{}) *IArchiveFile_Readdirnames_Call {
	return &IArchiveFile_Readdirnames_Call{Call: _e.mock.On("Readdirnames", n)}
}

func (_c *IArchiveFile_Readdirnames_Call) Run(run func(n int)) *IArchiveFile_Readdirnames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *IArchiveFile_Readdirnames_Call) Return(names []string, err error) *IArchiveFile_Readdirnames_Call {
	_c.Call.Return(names, err)
	return _c
}

func (_c *IArchiveFile_Readdirnames_Call) RunAndReturn(run func(int) ([]string, error)) *IArchiveFile_Readdirnames_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *IArchiveFile) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IArchiveFile_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type IArchiveFile_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *IArchiveFile_Expecter) Write(p interface{}) *IArchiveFile_Write_Call {
	return &IArchiveFile_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *IArchiveFile_Write_Call) Run(run func(p []byte)) *IArchiveFile_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *IArchiveFile_Write_Call) Return(n int, err error) *IArchiveFile_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *IArchiveFile_Write_Call) RunAndReturn(run func([]byte) (int, error)) *IArchiveFile_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewIArchiveFile creates a new instance of IArchiveFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIArchiveFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *IArchiveFile {
	mock := &IArchiveFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
